---
- hosts: all
  tasks:
  - name: update host file
    lineinfile:
      dest: "./files/hosts.txt"
      regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
      line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
      state: present
    become: yes
    with_items: "{{ groups.all }}"
    delegate_to: 127.0.0.1
